### ISSUE TITLE
Login through Github Auth Fails throwing a 500 error

### ISSUE THREAD

**Issue by mappmechanic** [shoonyatech/frontend.social#529] opened 2020-10-11 13:53 UTC
<img width="1717" alt="Screen Shot 2020-10-11 at 7 22 38 PM" src="https://user-images.githubusercontent.com/4088925/95680424-350ffd00-0bf7-11eb-96ce-a4e25f462b3f.png">

**Comment by souvikbasu** [comment] 2020-10-12 08:12
Thanks Rahat from bringing this up. Do you see any error in the network call response that returned 500 code?

**Comment by souvikbasu** [comment] 2020-10-13 09:38
@mappmechanic  the issue is fixed and merged now. Can you please check if it's working for you now. Seems to be working for me.

**Comment by NileshPatel17** [comment] 2020-10-13 09:40
@souvikbasu working for me as well..just verified. Thanks!

**Closed** 2020-10-22 07:11 UTC
